# Generated by Django 3.1.7 on 2021-03-22 15:54

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_index=True, max_length=20)),
                ('last_name', models.CharField(db_index=True, max_length=20)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('country', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('town', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('street', models.CharField(blank=True, db_index=True, max_length=30, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='frontend/images/')),
            ],
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('first_name', 'last_name'), name='idx_unique_full_name'),
        ),
    ]
