# Generated by Django 3.1.7 on 2021-03-21 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pocketbook', '0002_auto_20210321_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
