# Generated by Django 3.1.7 on 2021-03-21 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pocketbook', '0003_auto_20210321_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
